# -*- coding: utf-8 -*-
"""Picas y fijas Juan Calcetto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_J92IMfu7eaakai9CELNYlCNnytEIpj
"""

def pedir_numero(jugador):
  while True:
    num = input(f"Jugador {jugador}, digita un numero de 4 digitos distintos y diferentes a 0: ")

    if len(num) != 4 or not num.isdigit():
      print("Debe ser 4 dígitos")
      continue

    if '0' in num:
      print("No puede tener 0")
      continue

    if len(set(num)) != 4:
      print("No se puede repetir dígitos")
      continue

    return int(num)

def picas_y_fijas(secreto, intento):
  secreto_str = str(secreto).zfill(4)
  intento_str = str(intento).zfill(4)

  fijas = 0
  picas = 0

  for i in range(4):
    if intento_str[i] == secreto_str[i]:
      fijas += 1
    elif intento_str[i] in secreto_str:
      picas += 1
  return {"Picas": picas, "Fijas": fijas}

def jugar_picas_y_fijas():
  print("♡PICAS Y FIJAS♡")

  secreto1 = pedir_numero("1")
  secreto2 = pedir_numero("2")

  turno = 1
  jugador_actual = 1

  while True:
    print(f"\nTurno {turno} - Jugador {jugador_actual}")

    if jugador_actual == 1:
      intento = pedir_numero("1 (adivina adivinador)")
      resultado = picas_y_fijas(secreto2, intento)
    else:
      intento = pedir_numero("2 (adivina adivinador)")
      resultado = picas_y_fijas(secreto1, intento)

    print(f"Resultado: {resultado['FIJAS']} FIJAS, {resultado['PICAS']} PICAS")

    if resultado["FIJAS"] == 4:
      print(f"¡Jugador {jugador_actual} Ganaste bebeeeee!")
      break

    jugador_actual = 2 if jugador_actual == 1 else 1
    turno += 1

jugar_picas_y_fijas()